### ISSUE TITLE
[CODE] Fix "Recently Updated"

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#103]
On the homepage, there's a "Recently Updated" section which--theoretically--should render the most recent database entries.

**Comment by michaelknowles** [comment]
I'd like to work on this one.  Did you have any thoughts on how you'd like this to look?  How many entries to display (i.e. should it display _everything_ from the latest update)?

**Comment by billimarie** [comment]
Hi @michaelknowles, great questions. Feel free to implement according to your best judgement. I'd prefer a limit that works with the pagination, because--like you said--there are more & more attorneys being added.

**Comment by billimarie** [comment]
@michaelknowles solved this with PR #108
