### ISSUE TITLE
[CODE] Add "Race" Filter

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#113]
Background: please see #58 for a roadmap of the Additional Filters request.

We currently have a basic filtering system for filtering through prosecutors by **role**.

This feature request is for implementing an additional filter, which filters based upon a prosecutor's **race**.

What would be the best form element to render this as? Checkboxes? If you have any ideas, feel free to comment.

**Comment by shariq1989** [comment]
I'd like to pursue this. I think checkboxes would be a good solution

**Comment by billimarie** [comment]
Hi @shariq1989, thanks for volunteering. I have assigned you to this issue; please feel free to reach out if you have any questions.

You might want to take a look at #125, which is the checkbox for genders.

**Comment by shariq1989** [comment]
I forgot to link this to the PR (is that what you are supposed to do?).

**Comment by billimarie** [comment]
Absolutely no worries; I can close this issue officially.

If you want to be fancy in the future, just use a keyword like "fixes," "resolves," or "closes" in your PR, then tag the issue number. It will close the issue once merged automatically. [(more info)](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords)

**Comment by billimarie** [comment]
Closed with #140
