### ISSUE TITLE
[CODE] Convert date format

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#13]
re: appointed date (see US Attorneys)

Convert .json dates to human-friendly `month day, year` format
(conversely: change .json dates to human-friendly format. potential issue: organization)

**Comment by M-ZubairAhmed** [comment]
i will take this one

**Comment by billimarie** [comment]
Hi @M-ZubairAhmed, thanks for checking it out.

Each attorney entry in the database is formatted in JSON:
`{
    "_id": {
        "$oid": "5919ed1c734d1d1cd0be9d88"
    },
    "attorney-id": "ua-al-m",
    "name": "A. Clark Morris",
    "role": "U.S. Attorney",
    "state": "Alabama",
    "district": "Middle District of Alabama",
    "appointed": "2017-03-11"
}`

As you'll notice, the "appointed date" is just a string. Hopefully this can be changed so that in the future, a user will be able to use the app to filter through dates. If you have an idea of how to do this, please feel free to submit a pull request.

**Comment by callan-stretton** [comment]
I'll see if I can figure it out...

**Comment by extremelypenguin** [comment]
Hey, i'd be interested in doing this. Where is the json located?

**Comment by Thai56** [comment]
In api/data/usAttorneys.js I changed the "appointed" date to be a unix time stamp so that it would be easier to sort. In client/templates/sections/current-prosecutors.html I updated the appointed section to display month-day-year. When I open up localhost:3000 I am not able to see anything.

**Comment by billimarie** [comment]
Thanks for the assistance, everyone. Closing out thanks to @Thai56's pull-request: #31
