### ISSUE TITLE
[CODE] Create REST API

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#15]
- [ ] [Node.js RESTful API](https://www.codementor.io/olatundegaruba/nodejs-restful-apis-in-10-minutes-q0sgsfhbd)
  * [ ] beyond prototype: Amazon API Gateway
- [ ] Postman
- [ ] MongoDB

**Comment by Vishwajeetsinh98** [comment]
Please explain from where we need to access the data for the API? I'm willing to submit a pull request for this issue.

**Comment by billimarie** [comment]
Hi @Vishwajeetsinh98, thanks for checking this out.

Unfortunately there is no complete data source--we are just making our own based on manual research. You can see our results here (on an older branch): https://github.com/billimarie/light-pollution/blob/gh-pages/data/prosecutors.json

We're hoping to update this to something more elegant when we get more data. If you have any ideas, please feel free to submit a pull request. For now, the data we create is housed on mLab.com in JSON format:

```
{
    "_id": {
        "$oid": "5919ed1c734d1d1cd0be9d88"
    },
    "attorney-id": "ua-al-m",
    "name": "A. Clark Morris",
    "role": "U.S. Attorney",
    "state": "Alabama",
    "district": "Middle District of Alabama",
    "appointed": "2017-03-11"
}
```

**Comment by DanielStoica85** [comment]
I might be able to help with this, but I would need you to add more details (requirements).

**Comment by AbiSadhasivam** [comment]
Is this still open?

**Comment by billimarie** [comment]
Hi everyone,

This issue is now closed. Please see this pull request for more information: https://github.com/billimarie/prosecutor-database/pull/27
