### ISSUE TITLE
[CODE] Previous Prosecutors

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#152]
In tandem with the Design issue (#151), the unix timestamp must be converted into a user-friendly format:

<img width="506" alt="Screen Shot 2020-10-06 at 4 22 01 AM" src="https://user-images.githubusercontent.com/6895471/95196042-4b97fd80-078c-11eb-85bf-7d22f0716444.png">

You can take a look at how the `appointed` code is rendered on the Attorney Cards.

This is a great issue for a beginner. If you are an advanced developer (or consider this to be an easy fix), please feel free to check out our more complicated issues.

**Comment by blambert1080** [comment]
Hey do you mind if I take this one?

**Comment by billimarie** [comment]
@blambert1080 thank you for volunteering to contribute. I have assigned this issue to you; feel free to reach out if you have any questions.

**Comment by blambert1080** [comment]
Do you have any data that I can upload with previous prosecutors. I couldn't find any data to load in my local to test but I may be missing it.
