### ISSUE TITLE
[DATA] Complete installation documentation

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#4]
Update wiki with complete steps on how to contribute

**Comment by ashleyamin** [comment]
Hey Billimarie - this sounds like a cool and impactful project! I wanted to contribute, but it took me a while to find the installation documentation. I'd suggest moving it to the main README.md so others don't need to dig when just getting started. I'll take a look at the other issues too.

**Comment by billimarie** [comment]
Hi @ashleyamin,

Thanks for the recommendation. I'm hoping to restructure the repo sometime this week--as it's out of date with our current/local work, since we've migrated from Meteor.js to Drupal 8 for easier data management. I'd love any assistance you can offer for installation documentation. Please feel free to send me an email at work@billimarie.com.

Best,
Billimarie

**Comment by billimarie** [comment]
Closing, as I've updated the repo to reflect the aforementioned changes.
