### ISSUE TITLE
[BUG] Change "U.S. Attorney" to "US Attorney"

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#61]
Filter issue

**Comment by aminamos** [comment]
@billimarie where should this be updated?

**Comment by agnelnieves** [comment]
Hello @billimarie Did the fix, but not letting me push. Permission denied

**Comment by billimarie** [comment]
Hi @aminamos @agnelnieves, thanks for your interest. This needs to be updated in the dataset, which is located on mLab. I assigned it to myself & will try to get that done by the end of the month.

If you'd like to contribute, I'll be adding more issues as I come across them. Please feel free to open up a ticket if you have a suggestion for improving the app.
