### ISSUE TITLE
[BUG] Mobile: "Vote" Ribbon

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#65]
On mobile view of the app, the "vote" ribbon gets in the way of the user experience.

(Additionally: need new link for the ribbon. Suggestions?)

**Comment by taylor-brudos** [comment]
Hi!  Since voting for prosecutors depends on your county/state, I think we should use this link which is an official US government website that instructs how to vote and provides links to do so:  `https://www.usa.gov/register-to-vote`.

**Comment by taylor-brudos** [comment]
I'm working on updating the link and fixing the mobile view

**Comment by taylor-brudos** [comment]
Here is the PR for updating the vote link:  https://github.com/billimarie/prosecutor-database/pull/69

**Comment by taylor-brudos** [comment]
Here is the PR for updating the mobile ribbon UX: https://github.com/billimarie/prosecutor-database/pull/70

**Comment by billimarie** [comment]
Thank you, @taylor-brudos! Closing this issue, as you've solved it in both PRs.
