### ISSUE TITLE
[APP] Fix "Appointed" Date

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#83]
Update code to render Appointed dates

**Comment by hicks2evan** [comment]
Hey, first time here. Mind if I pick this one up?

**Comment by billimarie** [comment]
@hicks2evan Go for it! Please feel free to ping me if you have any questions (getting setup locally, rendering data on a local instance, etc).

**Comment by hicks2evan** [comment]
Hey @billimarie thanks for the quick response. I got the repo pulled and installed meteor and started the app. Looks like my local Mongo might not have any data...? Tips on seeding some test data?

**Comment by billimarie** [comment]
Got you covered: see ["To play around with data"](https://github.com/billimarie/prosecutor-database/blob/master/DOCS.md#4-web-app-development)
